inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*

Style/Documentation:
  Enabled: false

LineLength:
  Enabled: false

Lambda:
  Enabled: false

MethodLength:
  Enabled: false

BlockLength:
  Enabled: false
